### ISSUE TITLE
Add support of `pyproject.toml` for configuration

### ISSUE THREAD

**Issue by pivoshenko** [volopivoshenko/poetry-plugin-dotenv#214]
- [x] I have searched the [issues] of this repository and believe that this is not a duplicate.
- [x] I have searched the [documentation] and believe that my question is not covered.

Use `pyproject.toml` to load configuration variables as an alternative to env variables:
- `POETRY_DONT_LOAD_DOTENV`
- `POETRY_DOTENV_LOCATION`

```toml
[tool.poetry.plugins.dotenv]
ignore = false  # default
location = ""  # default
```

[documentation]: https://github.com/volopivoshenko/poetry-plugin-dotenv

[issues]: https://github.com/volopivoshenko/poetry-plugin-dotenv/issues
